# Generated by Django 2.1 on 2018-10-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_answer_q_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('multiple-choice', 'Multiple Choice'), ('true-false', 'True/False'), ('select-multiple', 'Select Multiple'), ('likert', 'Likert')], default='multiple-choice', help_text='Select a question type.', max_length=200),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
