# Generated by Django 2.1 on 2018-10-17 19:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20181017_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='q_id',
        ),
        migrations.RemoveField(
            model_name='response',
            name='a_id',
        ),
        migrations.RemoveField(
            model_name='response',
            name='q_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='q',
            field=models.ForeignKey(help_text='Associated question.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.Question'),
        ),
        migrations.AddField(
            model_name='response',
            name='a',
            field=models.ForeignKey(help_text='Survey response.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.Answer'),
        ),
        migrations.AddField(
            model_name='response',
            name='q',
            field=models.ForeignKey(help_text='Survey question.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(help_text='Answer.', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(help_text='Question text.', max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('multiple-choice', 'Multiple Choice'), ('true-false', 'True/False'), ('select-multiple', 'Select Multiple'), ('likert', 'Likert')], default='multiple-choice', help_text='Question type.', max_length=200),
        ),
        migrations.AlterField(
            model_name='response',
            name='free_resp',
            field=models.CharField(help_text='Path to cropped free response.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this response.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='scan_resp',
            field=models.CharField(help_text='Path to full card scan.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp of scan.'),
        ),
    ]
