# Generated by Django 2.1 on 2018-10-17 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20181017_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of survey.', max_length=200, null=True)),
                ('desc', models.CharField(help_text='Description of survey.', max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='survey',
            field=models.ForeignKey(help_text='Survey name.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.Survey'),
        ),
    ]
