# Generated by Django 2.1 on 2018-10-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20181017_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='scan_resp',
            new_name='scan',
        ),
        migrations.RemoveField(
            model_name='response',
            name='free_resp',
        ),
    ]
