# Generated by Django 2.1.2 on 2018-11-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20181031_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='scan',
        ),
        migrations.AddField(
            model_name='response',
            name='back',
            field=models.CharField(help_text='Path to full card scan.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='front',
            field=models.CharField(help_text='Path to full card scan.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='age',
            field=models.CharField(choices=[('under-18', 'Under 18.'), ('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-54', '45-54'), ('55-64', '55-64'), ('65-plus', '65+.')], default='25-34', help_text='Age classes.', max_length=25),
        ),
        migrations.AlterField(
            model_name='response',
            name='home',
            field=models.CharField(choices=[('urban', 'Urban'), ('suburban', 'Suburban'), ('rural', 'Rural')], default='urban', help_text='Type of location respondant calls home.', max_length=10),
        ),
        migrations.AlterField(
            model_name='response',
            name='zip_code',
            field=models.CharField(help_text='ZIP code.', max_length=10, null=True),
        ),
    ]
