# Generated by Django 2.1.2 on 2018-11-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20181109_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='a',
        ),
        migrations.AddField(
            model_name='response',
            name='a',
            field=models.ManyToManyField(help_text='Survey response.', to='survey.Answer'),
        ),
    ]
