# Generated by Django 2.1.2 on 2018-11-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20181112_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='back',
            field=models.FilePathField(help_text='Path to card back scan.', match='.*-back\\.png$', null=True, path='18.85.45.120/static/cards/', recursive=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='front',
            field=models.FilePathField(help_text='Path to card front scan.', match='.*-front\\.png$', null=True, path='18.85.45.120/static/cards/', recursive=True),
        ),
    ]
