# Generated by Django 2.1.2 on 2018-11-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_auto_20181112_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='type',
            new_name='question_type',
        ),
    ]
