# Generated by Django 2.1.2 on 2018-11-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0021_auto_20181112_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='age',
            field=models.CharField(choices=[('n', 'Not specified'), ('under-18', 'Under 18.'), ('18-24', '18-24'), ('25-34', '25-35'), ('35-44', '36-44'), ('45-54', '45-54'), ('55-64', '55-64'), ('65-plus', '65+.')], default=None, help_text='Age classes.', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='gender',
            field=models.CharField(choices=[('n', 'Not specified'), ('male', 'Male'), ('female', 'Female'), ('nonbinary', 'Nonbinary')], default=None, help_text='Gender identity.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='home',
            field=models.CharField(choices=[('n', 'Not specified'), ('urban', 'Urban'), ('suburban', 'Suburban'), ('rural', 'Rural')], default=None, help_text='Type of location respondant calls home.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='zip_code',
            field=models.CharField(default=None, help_text='ZIP code.', max_length=10, null=True),
        ),
    ]
