# Generated by Django 2.1.2 on 2018-11-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_auto_20181112_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='home',
            field=models.CharField(blank=True, choices=[('n', 'Not specified'), ('urban', 'Urban'), ('suburban', 'Suburban'), ('rural', 'Rural')], default=None, help_text='Type of location respondant calls home.', max_length=10, null=True),
        ),
    ]
