# Generated by Django 2.1.3 on 2018-11-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0025_auto_20181112_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='age',
            field=models.CharField(blank=True, choices=[('', ''), ('under-18', 'Under 18.'), ('18-24', '18-24'), ('25-34', '25-35'), ('35-44', '36-44'), ('45-54', '45-54'), ('55-64', '55-64'), ('65-plus', '65+.')], default=None, help_text='Age classes.', max_length=25),
        ),
        migrations.AlterField(
            model_name='response',
            name='gender',
            field=models.CharField(blank=True, choices=[('', ''), ('nonbinary', 'Nonbinary'), ('female', 'Female'), ('male', 'Male')], default=None, help_text='Gender identity.', max_length=25),
        ),
        migrations.AlterField(
            model_name='response',
            name='home',
            field=models.CharField(choices=[('', ''), ('urban', 'Urban'), ('suburban', 'Suburban'), ('rural', 'Rural')], default=None, help_text='Type of location respondant calls home.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='zip_code',
            field=models.CharField(blank=True, default=None, help_text='ZIP code.', max_length=10),
        ),
        migrations.AlterField(
            model_name='survey',
            name='desc',
            field=models.CharField(help_text='Description of survey.', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(help_text='Name of survey.', max_length=50, null=True),
        ),
    ]
