# Generated by Django 2.1.3 on 2018-11-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0026_auto_20181112_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='zip_code',
            field=models.CharField(default=None, help_text='ZIP code.', max_length=10, null=True),
        ),
    ]
