# Generated by Django 2.1.3 on 2018-11-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0028_auto_20181112_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='age',
            field=models.CharField(blank=True, choices=[('', ''), ('under-18', 'Under 18.'), ('18-24', '18-24'), ('25-34', '25-35'), ('35-44', '36-44'), ('45-54', '45-54'), ('55-64', '55-64'), ('65-plus', '65+.')], default=None, help_text='Age classes.', max_length=20, null=True),
        ),
    ]
