# Generated by Django 2.1.2 on 2018-11-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0030_auto_20181112_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='back',
            field=models.FilePathField(help_text='Path to card back scan.', match='.*-back\\.png$', null=True, path='/static/cards/', recursive=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='front',
            field=models.FilePathField(help_text='Path to card front scan.', match='.*-front\\.png$', null=True, path='/static/cards/', recursive=True),
        ),
    ]
