# Generated by Django 2.1.2 on 2018-11-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0031_auto_20181113_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='back',
            field=models.FilePathField(help_text='Path to card back scan.', match='.*-back\\.png$', null=True, path='/static/cards/fg2/', recursive=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='front',
            field=models.FilePathField(help_text='Path to card front scan.', match='.*-front\\.png$', null=True, path='/static/cards/fg2/', recursive=True),
        ),
    ]
