# Generated by Django 2.1 on 2018-10-17 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20181017_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='q_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.Question'),
        ),
    ]
