# Generated by Django 2.1.2 on 2018-11-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20181022_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='age',
            field=models.CharField(choices=[('less-18', 'Less than 18.'), ('18-24', '18-24'), ('25-34', '25-34'), ('35-44', '35-44'), ('45-54', '45-54'), ('55-64', '55-64'), ('more-65', 'Greater than 65.')], default='25-34', help_text='Age classes.', max_length=25),
        ),
        migrations.AddField(
            model_name='response',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('nonbinary', 'Nonbinary')], default='nonbinary', help_text='Gender identity.', max_length=200),
        ),
        migrations.AddField(
            model_name='response',
            name='home',
            field=models.CharField(choices=[('urban', 'Urban'), ('suburban', 'Suburban'), ('nonbinary', 'Nonbinary')], default='urban', help_text='Type of location respondant calls home.', max_length=10),
        ),
        migrations.AddField(
            model_name='response',
            name='zip_code',
            field=models.CharField(help_text='ZIP code.', max_length=5, null=True),
        ),
    ]
