# Generated by Django 2.1.2 on 2018-11-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_auto_20181112_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='q',
        ),
        migrations.AddField(
            model_name='answer',
            name='q',
            field=models.ManyToManyField(help_text='Associated question.', to='survey.Question'),
        ),
        migrations.AlterField(
            model_name='response',
            name='back',
            field=models.FilePathField(help_text='Path to card back scan.', match='.*-back\\.png$', null=True, path='/home/cards/fg1/q1/', recursive=True),
        ),
    ]
