# Generated by Django 2.1.2 on 2018-11-12 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_auto_20181112_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_question', models.CharField(help_text='Free response question text.', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='free_resp',
            field=models.CharField(help_text='Text of free response.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='free_q',
            field=models.ForeignKey(help_text='Free response question.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.FreeQuestion'),
        ),
    ]
