# Generated by Django 2.1.2 on 2018-11-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0024_auto_20181112_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='free_resp',
            field=models.CharField(blank=True, help_text='Text of free response.', max_length=200, null=True),
        ),
    ]
